name: Test
on: [push]

jobs:

  test:
    name: Test on push
    runs-on: ubuntu-latest
    steps:
    - name: setup env
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/go"
        echo "::add-path::${{ github.workspace }}/go/bin"

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get test dependencies
      id: get-test-deps
      run: |
        go get -v -t -d ./...
        go get -v -t -u golang.org/x/lint/golint \
          honnef.co/go/tools/cmd/staticcheck \
          github.com/golangci/golangci-lint/cmd/golangci-lint \
          github.com/fzipp/gocyclo
    - name: go test
      run: go test .

    - name: golangci-lint
      run: golangci-lint run .
